[book]
authors = ["Profesor Maximiliano Chaves"]
language = "es"
multilingual = false
src = "src"
title = "Programacion II"
description = "Apunte acompa√±amiento de el espacio curricular Programacion II."
