[book]
authors = ["Profesor Maximiliano Chaves"]
language = "es"
multilingual = false
src = "src"
title = "Programacion I"
description = "Apunte acompa√±amiento de el espacio curricular Programacion I."

[output.html]
theme = "mytheme"